### ISSUE TITLE
Release the source code

### ISSUE THREAD

**Issue by Tom-Neverwinter** [bitclout/run#15]
This code branch is probably in violation of the GPL v2 or v3 or 

The MIT License used in bitcoin is widely used across open source software projects to enable innovation and collaboration.

source must be provided and a copy of the license. 

**GitHub Community Guidelines**

**Comment by jazzyjackson** [comment]
The MIT license of Bitcoin does not require this, so it’s probably not in violation. Of course we are all waiting for the source, no need for the “must provide” language.

**Comment by codeape** [comment]
Well here is the bitcoin source for anyone to read: https://github.com/bitcoin/bitcoin

Where is the source for the bitclout "coin"? 

@jazzyjackson ... you need the source to know that the currency is reliable ... if you did not know that. If it is not reliable it has no use as a currency. It is worthless. It is monopoly money.

**Comment by jazzyjackson** [comment]
Wasn't arguing any of those points, just pointing out MIT is not a viral license like GPL, forks are not required to have the same license.

**Comment by codeape** [comment]
I was reacting because you are downplaying the need for source. @jazzyjackson 

No serious crypto currency release the source of the node or the miner after going public they do it before. BitClout has already done $400M on this. No source. Only silence.

If you are not arguing ... what are you even doing here?

**Comment by codeape** [comment]
@jazzyjackson ... sorry for the harsh tone ... but I am not happy with this situation.

**Comment by wpeckr** [comment]
The "core-obf" (obfuscated presumably) doesn't appear to be a fork of Bitcoin. The way this is being presented is obviously deigned to make people believe that it is open source, which is deceptive at best.

**Comment by jazzyjackson** [comment]
No worries, I have to take a deep breath on here too. Lots of places to debate the trustworthiness of the project, it would be nice to see the github issues page used to people setting up nodes.

The way I look at it, an anonymous stranger online (diamondhands/maebeam) made big promises, and that's all the assurance I have that this is real. My running theory is that the site went live weeks before they planned because every other social network is experimenting with micropayments too, and that explains all the unfulfilled promises to me. 

Thanks for pointing out obf=obfuscated.

Anyway, see ya'll in the closed issues bin.

**Comment by wpeckr** [comment]
<img width="463" alt="obfuscated" src="https://user-images.githubusercontent.com/60858013/115913300-6ab35f80-a43e-11eb-83b3-469b935372d0.png">

A cursory browse of the binary I obtained does appear to be at least somewhat packed or obfuscated, I would highly recommend that nobody run this on their system under any circumstances. 

I am analyzing `MD5(bitclout-obf/core/backend)= 4344feebd7fc3127a8fd044bd028cf3e`.

**Comment by wpeckr** [comment]
`MISSING BlockCypher API key, which means we can't show balances on the Buy BitClout page or support double-spend detection. Pass --block_cypher_api_key to enable this functionality`

Sounds decentralized.

**Comment by wpeckr** [comment]
On startup, it attempts to make a series of DNS queries to a truly colossal number of domain names in the format `bitclout-seed-$n`, I've seen several hundred so far. Only `bitclout-seed-2.io` and `bitclout-seed-4.io` seem to have A records, which are then used to connect on TCP 17000.

**Comment by maebeam** [comment]
If you'd like to discuss the project in general you can join the community-run discord at http://discord.gg/bitclout. GitHub Issues is for actual issues.
