### ISSUE TITLE
Update domain name for Nginx config (removing bitpop mentions)

### ISSUE THREAD

**Issue by thealialexander** [bitclout/run#5]
When setting up a node on a cloud server, the README instructions only work for the one “bitpop.cash” domain and aren’t generalized for developers using their own domain names.

I assume this is a carryover from the development days. We think this should be updated from “bitpop.cash” to a more general _whatever domain_ name you’re using. I have been on the bitpop server in the past.

**Comment by connerdouglass** [comment]
Can confirm, using "bitpop.cash" causes routing issues. Both our site domain and the "api." subdomain get routed to the frontend. Every AJAX call on the frontend returns the Angular `index.html` file.

Works flawlessly when we use our domain instead of "bitpop.cash"

Suggested fix in Issue https://github.com/bitclout/run/pull/6

**Comment by chafreaky** [comment]
This has now been merged into `main`.

**Comment by maebeam** [comment]
Thanks for the report!
