### ISSUE TITLE
Not a real node

### ISSUE THREAD

**Issue by LinusAWozniak** [bitclout/run#7]
This has no source code, or anything similar. It's a docker image downloading and then running a precompiled binary. You're still dependent on their closed source API, and who knows what code could be included in the binary. Do _**NOT**_ use this. Bitclout is nothing more than a scam.

**Comment by therealjaredcodling** [comment]
u mad bro?

**Comment by LinusAWozniak** [comment]
Mad would be a bit of an overstatement. Annoyed would be an apt descriptor however. The people behind BitClout, whoever they might be, are scamming users, and they're not providing any actual source code in this, merely using GitHub to distribute binaries.

**Comment by EpicLPer** [comment]
Watch this issue get closed without any further comments from their side soon lol

**Comment by LinusAWozniak** [comment]
Hey @EpicLPer, this issue won't get closed, as most likely they'll out and out delete it. I'll also be blocked, as evidenced by Barnacules having the same thing happen with him.

Before that happens however, @therealjaredcodling, would you like to respond further? You replied with "u mad bro" and, when confronted with a logical argument, seemed to have left the conversation immediately. 

Cheers! - Linus

**Comment by ImDemonetized** [comment]
Whats up boys and girls. It's your boy Demonetized.
I can't wait to watch Bitclout burn from the inside.
Anyone want any coffee while I'm here?

**Comment by therealjaredcodling** [comment]
Haha oh Linus....

My comment reflected the likelihood that they care or didn't realize.

Your points aren't just valid; they're incredibly obvious; which is unfortunate, because this is pretty bad.

I did a lot of digging around; seeing where funds went from original pre-mining etc. I've never quite seen a ponzi quite like this; and was curious how they'd hide it all when opening up the source code. But as I expected, they just didn't lol.

**Comment by maebeam** [comment]
GitHub is not the place for this discussion.

**Comment by EpicLPer** [comment]
Actually... yes it is?

**Comment by codeape** [comment]
If you guys cant release the source or event talk abut the source ... this is not an open source project. You cant claim this to be a crypto currency project if it is not open source. 

Until the source is released you are producing and selling Monopoly money!

**Comment by LinusAWozniak** [comment]
> Haha oh Linus....
> 
> My comment reflected the likelihood that they care or didn't realize.
> 
> Your points aren't just valid; they're incredibly obvious; which is unfortunate, because this is pretty bad.
> 
> I did a lot of digging around; seeing where funds went from original pre-mining etc. I've never quite seen a ponzi quite like this; and was curious how they'd hide it all when opening up the source code. But as I expected, they just didn't lol.

Oh, my apologies then! I wasn't trying to get the people behind BitClout to change their ways, I was more intending this to be a warning to other GitHub users :D While they're obvious, some people very well might fall for them, and I was hoping to point them out. Most of the times I've heard someone respond "u mad bro?" is in an antagonistic manner in an attempt to dismiss a critique, so I assumed you were just a BitClout fan, so I'm very sorry for that! 



> GitHub is not the place for this discussion.

Except it is, you provide no legitimate means of contact other than an email, which is going to get less of a response I'd bet, and being that the issue is located on this GitHub repo, it's only fitting it take place here. You just don't want people openly critiquing your service, on a forum where you're trying to get more users.

**Comment by Kichura** [comment]
GitHub can always be used to give out criticism whether you like it or not. And using e-mails to contact people is just going to be a lack of response to this mankind. Thous i do not agree with what "maebeam" is doing in this case including closing this issue.

+ Everybody has the right to decide whether bitclout is ok or not since they will be on their own, however i myself do not wish to use this product for anything since i'm not a bitcoin-related/crypto-related user at all and never wish to be one.

**Comment by maebeam** [comment]
You're welcome to discuss the project in general on the community-run discord at http://discord.gg/bitclout, not our issue tracker.
